server:
  port: 8088

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://39.108.14.200:3306/aottrade?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 342@fj*&A
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.aotfx.mobile.dao.entity
  config-location:
  executor-type: simple
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






##开发配置
#spring:
#  profiles: dev
#
#  datasource:
#    url: jdbc:mysql://39.108.14.200:3306/aottrade?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 342@fj*&A
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    session:
#        store-type: none
#
#
#server:
#  port: 8088
#
#
#  ##mybatis-plus mapper xml 文件地址
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  ##mybatis-plus type-aliases 文件地址
#  type-aliases-package: com.aotfx.mobile.dao
#  executor-type: BATCH
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#commonDS:
#  # 配置初始化大小、最小、最大
#  initialSize: 2
#  minIdle: 2
#  maxActive: 5
#  #配置获取连接等待超时的时间
#  maxWait: 60000
#  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#  timeBetweenEvictionRunsMillis: 60000
#  #配置一个连接在池中最小生存的时间，单位是毫秒
#  minEvictableIdleTimeMillis: 60000
#
#  validationQuery: SELECT 'x'
#  testWhileIdle: true
#  testOnBorrow: false
#  testOnReturn: false
#  #打开PSCache，并且指定每个连接上PSCache的大小
#  poolPreparedStatements: true
#  maxPoolPreparedStatementPerConnectionSize: 5
#  #配置监控统计拦截的filters，去掉后监控界面sql无法统计
#  filters: stat,wall,slf4j
#  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  useGlobalDataSourceStat: true
#---



---